### PR TITLE
Fixes #539: Integrate grunt-scss-lint from #613

### LINKED ISSUE #539: Integrate SCSS-Lint?
https://github.com/causes/scss-lint

### PR DESCRIPTION
**Pull request by watilde**
Fixes #539.
I integrated grunt-scss-lint and fixed some warning by lint check.

### CODE REVIEW

**Comment by XhmikosR** [comment]
Can you rebase this?

**Comment by watilde** [comment]
@XhmikosR Sure, I've done rebase.

**Comment by XhmikosR** [comment]
There seems to be many newer versions out https://github.com/causes/scss-lint/releases/tag/v0.33.0

Anyway, I'm not against it but I'm not sure I like yet another Ruby dependency :/

/CC @twbs/ratchet for thoughts

**Comment by XhmikosR** [comment]
@watilde: we need another rebase.

**Comment by watilde** [comment]
@XhmikosR OK, I'm going to check the latest version of scss-lint and rebase.

**Comment by XhmikosR** [comment]
@watilde: ping

**Comment by XhmikosR** [comment]
@watilde: do you plan to rebase this and remove the dist files from the branch too?

**Comment by watilde** [comment]
@XhmikosR Let me try it now!

**Comment by watilde** [comment]
Since this PR is too old to rebase, I just closed it. If anyone has an interest, feel free to take it :)

**Pull request closed without merging**
