### PR TITLE
Fix push.js transition ending listener for Firefox

### PR DESCRIPTION
**Pull request by TouPye**
Firefox fire the event "transitionend"

https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Using_CSS_transitions#Detecting_the_completion_of_a_transition

### CODE REVIEW

**Comment by XhmikosR** [comment]
We need to make this a function which will use the right event based on the browser instead of duplicating code.

**Comment by XhmikosR** [comment]
Something like I'm trying to do in #491 but I don't like it so much yet thus not merged.

**Comment by cvrebert** [comment]
It's not clear if Android Firefox is officially supported (see http://goratchet.com/getting-started/). But this is the standard-compliant event name, so adding it seems like a good idea regardless.

**Comment by XhmikosR** [comment]
Well, duplicating things like that isn't nice. My solution seems to work, I just need some feedback.

**Comment by XhmikosR** [comment]
@Johann-S: can you confirm that this is redundant now in the current master?

**Comment by Johann-S** [comment]
Yes It's redundant, but i think we will have to fix **push.js** using ``getBrowserCapabilities`` to get
the right prefix and remove or add the right event listener for the right browser.

**Comment by XhmikosR** [comment]
Indeed. Can you make a new PR to tackle that please?

**Comment by Johann-S** [comment]
Yes sure I'll work on it !

But I'll also include my futur new PR to fix push.js when it will be merged on the refactoring (https://github.com/twbs/ratchet/pull/745) because I'll duplicate code to use ``getBrowserCapabilities``

**Comment by XhmikosR** [comment]
OK, closing this then and we'll try to merge #745 first.

**Pull request closed without merging**
