### PR TITLE
JS fixes

### PR DESCRIPTION
**Pull request by XhmikosR**
This is totally a **WIP**, but it works for me in both Firefox and Chome without any `TypeError`s.

/CC @connor @connors @fat 

Any suggestions are welcome.

PS. IE is broken after #446

### CODE REVIEW

**Comment by XhmikosR** [comment]
@hnrch02: any thoughts on this? Seems everyone else isn't available and this patch is very important to ensure everything works on most browsers.

Only thing I don't like is duplicating `getBrowserCapabilities` but we don't seem to have a common file.

**Comment by hnrch02** [comment]
Looks fine to me. Some way to share `getBrowserCapabilities` without duplicating it across files would be nice though, as you mentioned.

**Comment by XhmikosR** [comment]
The reason I didn't make that separate is I don't know if the new file will be redundant or not...

Otherwise I'll merge this as it is.

**Comment by Johann-S** [comment]
I think it would be great to have a common.js file because they are few pull requests which need this like : 
https://github.com/twbs/ratchet/pull/675
or
https://github.com/twbs/ratchet/pull/427

**Comment by XhmikosR** [comment]
How about we just merge this as it is and leave the refactoring for another PR? I'm not sure when I'll have some time to do it myself and it's a pity for Rachet to partially work on Webkit.

**Comment by Johann-S** [comment]
Yes i think it would be easy to do it in a separate RP. I'll work on it

**Comment by alinihad** [comment]
Please . Help me
بتاريخ 2015 2 3 10:46، جاء من "Johann" <notifications@github.com>:

**Comment by hnrch02** [comment]
@XhmikosR Fine by me.

**Comment by XhmikosR** [comment]
@Johann-S: please CC me if you make a PR to refactor stuff.

**Comment by Johann-S** [comment]
@XhmikosR yes i want to do that, but i created a PR yesterday (https://github.com/twbs/ratchet/pull/743) and my PR was closed because a common.js file already existed on this PR : https://github.com/twbs/ratchet/pull/675

So, i'm not sure if it's better to wait for the merge of this PR (https://github.com/twbs/ratchet/pull/675) or if i can begin my refactoring PR

**Comment by XhmikosR** [comment]
Personally I believe the refactoring should come first and the other PR
should be rebased after that.

**Pull request merged**
