### PR TITLE
support `file://` urls in push.js

### PR DESCRIPTION
**Pull request by artemave**
This enables phonegap integration (#553).

### CODE REVIEW

**Comment by XhmikosR** [comment]
Closing due to lack of reply from @artemave.

**Comment by edasque** [comment]
That's too bad. Phonegap developers are abandoning jQuery mobile but RatchetJS doesn't seem to be the solution if they can't support this via this PR or other work.

**Comment by XhmikosR** [comment]
@edasque: Well, I gave @artemave plenty of [time](https://github.com/twbs/ratchet/pull/558#issuecomment-40891522) to rebase and squash...

**Comment by artemave** [comment]
Sorry for not responding. I also realised that my comments above are rather negative. I apologize for that.

Now, I don't use Ratchet at the moment, but I am sure someone who _needs_ it to work on Phonegap can pick up this patch and get it into a mergable state.

**Comment by ebradbury** [comment]
@XhmikosR I opened a new PR with a squashed version. https://github.com/twbs/ratchet/pull/750

**Comment by XhmikosR** [comment]
Thanks, I'll check it out as soon as possible and close this one.

**Pull request closed without merging**
